### ISSUE TITLE
No nodes

### ISSUE THREAD

**Issue by oliverw** [PulsarCoin/Pulsar-Coin-Cryptocurrency#10]
`pulsard` has trouble maintaining even one single connection. I've never experienced something like this with any other coin. Can you provide a list of peers?

**Comment by Original-Tasty** [comment]
Hello, are you using the latest version v1.1.1?

**Comment by PulsarCoin** [comment]
Please download V1.1.2

Also, there are two new masternodes, add in the following to pulsar.conf:
addnode=137.220.60.11:5995
addnode=45.63.65.34:5995
