### ISSUE TITLE
Unable to build BDB 4.8 on macOS

### ISSUE THREAD

**Issue by basking-in-the-sun2000** [PulsarCoin/Pulsar-Coin-Cryptocurrency#13]
I'm getting an error when installing bdb
```
configure: WARNING: NO SHARED LATCH IMPLEMENTATION FOUND FOR THIS PLATFORM.
configure: error: Unable to find a mutex implementation
```

Found a similar issue opened on bitcoin, this might help solve it for others
https://github.com/bitcoin/bitcoin/issues/19411

Using that thread, I was able to build it using
`./contrib/install_db4.sh . --disable-mutexsupport`

**Comment by Original-Tasty** [comment]
Hello, thank you for the information! Closing it as you found a fix already.
