### ISSUE TITLE
Pulsar-qt Is Crashing even after reinstalling.

### ISSUE THREAD

**Issue by codercoins** [PulsarCoin/Pulsar-Coin-Cryptocurrency#14]
Everytime I load up Pulsar wallet it says loading block index and then loading wallet then crashes and never opens.
I checked for the block index location on my pc but can't find anything.
I would very much like to use this wallet please help. 

On first install I would like to add the wallet loaded up correctly and started syncing the blockchain.. But my computer died and thus now when I try to open to wallet to begin the sync again as I said it crashes after saying loading block index and then loading wallet.

**Comment by Original-Tasty** [comment]
Hello, what operation system are you on? (Windows, Linux, Mac etc..)

Are you facing the same issue?

**Comment by TylerAnder** [comment]
Closing the issue as it's been a while - please  feel free to re open it if you still need assistance.
