### ISSUE TITLE
Segment violation (`generated core')

### ISSUE THREAD

**Issue by Ursus1416** [PulsarCoin/Pulsar-Coin-Cryptocurrency#16]
I have a problem with the wallet, my hard drive was full while I had the wallet open. Corrected the filling. Restart the computer.
When trying to open the wallet I get the error
Segment violation (`generated core')
and does not open the wallet.
I am using Ubuntu 20.04.5.
What I can do?

**Comment by TylerAnder** [comment]
Hello, have you tried to delete all files (except the wallet.dat) and to try to re download the whole blockchain again?
