### ISSUE TITLE
Cant install.

### ISSUE THREAD

**Issue by Mich341** [PulsarCoin/Pulsar-Coin-Cryptocurrency#4]
I cant install with script on ubuntu 20/04 but just that
![image](https://user-images.githubusercontent.com/98632773/151648254-45a2210b-bacd-4ede-a507-7a1cb17e6fb7.png)

**Comment by Mich341** [comment]
#!/bin/bash -ev

gcc --version
g++ --version

./contrib/install_db4.sh `pwd`
#flags arent being picked up, so need to link
sudo ln -sf `pwd`/db4/include /usr/local/include/bdb4.8
sudo ln -sf `pwd`/db4/lib/*.a /usr/local/lib
./autogen.sh
./configure --with-gui=qt5
make -j$(nproc)
make check

**Comment by Original-Tasty** [comment]
Use the depends folder to build a ''static" wallet instead of compiling directly with autogen and configure

**Comment by Mich341** [comment]
> > 
> 
> Thank you for letting us know about your problem! I found out that a few files were left out of the first upload to github. We'll make sure to get these found and updated within the next few days. Thank you again!

more thanks, no need, this so important after ANN on bittalk) 130k premined )
