### ISSUE TITLE
Build For aarch64/arm64

### ISSUE THREAD

**Issue by wongfihung2** [PulsarCoin/Pulsar-Coin-Cryptocurrency#5]
I have trying to build on arm64[ubuntu] but failed.

First error: must include deque 
>> #include deque
After deque i include, more errors generated.
like _1, _2, _3 is not decleared in this scoope.
Then i edit the source code by dissabling line containing all errors.
and the pulsard, pulsar-cli, and pulsar-tx builded.
but, I have problem again in the network difficulty.
The based diffculty on this time is 2.3 or 2.8
but in my wallet th diffculty is 186035.6771501942(this like sha256d network diffculty and is too high)

How to fix...???
please help me...

I need for my raspberry pi for running daemon wallet.

**Comment by blackmennewstyle** [comment]
I don't think this project is a serious one, i have some experience with crypto projects and this one looks like a lot like Raptoreum. You can't build arm64 wallet for Raptoreum and the devs does not seem to really care about it. I think here we have the same kind  of people but probably worst. The fact you did not receive any response after 24 days tells a lot. You can always judge about the strength of project when you interact with its team devs. Here, well...

**Comment by Original-Tasty** [comment]
> 

Hello, you must first build the dependencies (from the depends folder) in order to compile a static wallet.

**Comment by Original-Tasty** [comment]
> I have trying to build on arm64[ubuntu] but failed.
> 
> First error: must include deque
> 
> > > #include deque
> > > After deque i include, more errors generated.
> > > like _1, _2, _3 is not decleared in this scoope.
> > > Then i edit the source code by dissabling line containing all errors.
> > > and the pulsard, pulsar-cli, and pulsar-tx builded.
> > > but, I have problem again in the network difficulty.
> > > The based diffculty on this time is 2.3 or 2.8
> > > but in my wallet th diffculty is 186035.6771501942(this like sha256d network diffculty and is too high)
> 
> How to fix...??? please help me...
> 
> I need for my raspberry pi for running daemon wallet.

Please use this version for the fix on Qt Arm Aarch64 & i686 fix
https://github.com/PulsarCoin/Pulsar-Coin-Cryptocurrency/releases/tag/v1.1.1
