### ISSUE TITLE
Splash screen loading, then wallet closes

### ISSUE THREAD

**Issue by GetRekt69420** [PulsarCoin/Pulsar-Coin-Cryptocurrency#9]
as title states.. the splash screen of Pulsar wallet shows.. with "loading wallet...." at the bottom.. and then disappears and closes.
it was working and operating perfectly for several days.. and i accidently closed the wallet.. (_which shouldn't be a problem to begin with_) and went to open it back up.. and this issue is what I am met with.. 
I've tried everything I know to do.. from uninstalling and reinstalling.. deleting temp folders... make sure of firewall exceptions.. everything.. 

**_this is the only thing it will do now... just the splash screen and then closes_**
![plsrsplash_crash](https://user-images.githubusercontent.com/83239093/156895498-72a02cd7-0795-4e33-af3a-8bcecb555686.png)

**Comment by GetRekt69420** [comment]
i fixed the issue.. i deleted everything i could find in the windows registry, (_run regedit - \HKEY_LOCAL_MACHINE\SOFTWARE\Classes\_) and seems to work fine now, my coins and everything safe and sound

**Comment by Original-Tasty** [comment]
> I fixed the issue.. I deleted everything i could find in the windows registry that was pulsar related, (_run regedit - and deleted pulsar directory in HKEY_LOCAL_MACHINE\SOFTWARE\Classes\pulsar_) and seems to work fine now, my coins and everything safe and sound

Hello, sorry for I didnt see your issue at time. Glad it is fixed now, and ty for explaining how you<ve fixed it
